# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9561e49a1fbefaa0373829c7cdb29ae26ffe9fe45017152cea8ca28ed3fe6249fd0055824715a18c36d27daa4abc3dfd9812f67490305c40bbbacc73efdff7b2

test:
  secret_key_base: 3fa8aa362a141a7b5fb8af38cc535d04a6d34105ace602153d4ec0f3c735389e21f3f8c2df8d882261b984e9dd61a007ac9ed41c1556e6f49b357edb30755fa7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
